---
title: Bouncing Buffers
name: papadanku's shader programming blog
description: Shader development
github_username: papadanku

theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap